format_code_in_doc_comments = true
reorder_impl_items = true
wrap_comments = true
empty_item_single_line = false
imports_granularity = "Module"
# normalize_comments = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
